### ISSUE TITLE
A question on time and memory requirement of a helper script "database_download.py"

### ISSUE THREAD

**Issue by ilnamkang** [leylabmpi/Struo2#16]
Thank you for a great tool!

Since I'd like to use the pre-built GTDB R202 database, I'm trying using the helper script as below.  

./util_scripts/database_download.py -t 4 -r 202 -d kraken2 metadata taxdump phylogeny -- custom_dbs

This command has been working without any errors, but it seems to require >48 hrs of running time and >200 Gbp of memory.

Is this usual?

If not, are there any ways to reduce running time and/or memory usage?

Thanks in advance.

**Comment by nick-youngblut** [comment]
It must be loading files into memory prior to writing. I will have a look

**Comment by nick-youngblut** [comment]
OK, I've updated the code so it should stream the data in chunks instead of loading it all into memory. Reopen if there's still a problem

**Comment by ilnamkang** [comment]
Thank you for a quick update!!

But unfortunately, I've encountered errors during running the updated code.

Below I attach the commands and log files. One is from Python2 and the other is from Python3. I tried both and the error messages were different between Python2 and Python3.

(Python2 command; default Python version 2.7.17)
nohup ./util_scripts/database_download.py -t 4 -r 202 -d kraken2 metadata taxdump phylogeny -- custom_dbs > dw2.log 2>&1 &

(Python3 command; version 3.8.0)
nohup python3 ./util_scripts/database_download.py -t 4 -r 202 -d kraken2 metadata taxdump phylogeny -- custom_dbs > dw3.log 2>&1 & 

### Python2 log
\-----------------------
nohup: ignoring input
2022-02-08 10:18:25,385 - Starting new HTTP connection (1): ftp.tue.mpg.de
2022-02-08 10:18:27,137 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release202/kraken2 HTTP/1.1" 301 275
2022-02-08 10:18:27,466 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release202/kraken2/ HTTP/1.1" 200 5039
2022-02-08 10:18:27,518 - Starting new HTTP connection (1): ftp.tue.mpg.de
2022-02-08 10:18:27,524 - Starting new HTTP connection (1): ftp.tue.mpg.de
2022-02-08 10:18:27,528 - Starting new HTTP connection (1): ftp.tue.mpg.de
2022-02-08 10:18:27,531 - Starting new HTTP connection (1): ftp.tue.mpg.de
2022-02-08 10:18:28,876 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release202/kraken2/database100mers.kraken HTTP/1.1" 200 273571194
2022-02-08 10:18:28,878 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release202/kraken2/database.kraken.md5 HTTP/1.1" 200 50
2022-02-08 10:18:28,878 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release202/kraken2/database.kraken HTTP/1.1" 200 61541911507
2022-02-08 10:18:28,879 - File written: custom_dbs/GTDB_release202/kraken2/database.kraken.md5
2022-02-08 10:18:28,880 - Starting new HTTP connection (1): ftp.tue.mpg.de
2022-02-08 10:18:28,883 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release202/kraken2/database75mers.kraken HTTP/1.1" 200 481357069
2022-02-08 10:18:30,234 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release202/kraken2/database75mers.kmer_distrib HTTP/1.1" 200 8092021
2022-02-08 10:18:58,453 - File written: custom_dbs/GTDB_release202/kraken2/database75mers.kmer_distrib
2022-02-08 10:18:58,463 - Starting new HTTP connection (1): ftp.tue.mpg.de
2022-02-08 10:18:59,814 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release202/kraken2/database150mers.kraken HTTP/1.1" 200 353523859
2022-02-08 10:29:26,042 - File written: custom_dbs/GTDB_release202/kraken2/database100mers.kraken
2022-02-08 10:29:26,048 - Starting new HTTP connection (1): ftp.tue.mpg.de
2022-02-08 10:29:28,994 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release202/kraken2/database150mers.kmer_distrib HTTP/1.1" 200 6688497
2022-02-08 10:29:42,714 - File written: custom_dbs/GTDB_release202/kraken2/database150mers.kmer_distrib
2022-02-08 10:29:42,724 - Starting new HTTP connection (1): ftp.tue.mpg.de
2022-02-08 10:29:44,083 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release202/kraken2/database200mers.kraken HTTP/1.1" 200 258230018
2022-02-08 10:34:04,063 - File written: custom_dbs/GTDB_release202/kraken2/database150mers.kraken
2022-02-08 10:34:04,067 - Starting new HTTP connection (1): ftp.tue.mpg.de
2022-02-08 10:34:05,702 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release202/kraken2/database200mers.kmer_distrib HTTP/1.1" 200 4318492
2022-02-08 10:34:17,371 - File written: custom_dbs/GTDB_release202/kraken2/database200mers.kmer_distrib
2022-02-08 10:34:17,380 - Starting new HTTP connection (1): ftp.tue.mpg.de
2022-02-08 10:34:18,740 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release202/kraken2/database250mers.kraken HTTP/1.1" 200 258893052
2022-02-08 10:39:35,171 - File written: custom_dbs/GTDB_release202/kraken2/database200mers.kraken
2022-02-08 10:39:35,175 - Starting new HTTP connection (1): ftp.tue.mpg.de
2022-02-08 10:39:37,054 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release202/kraken2/database250mers.kmer_distrib HTTP/1.1" 200 4007536
2022-02-08 10:39:52,310 - File written: custom_dbs/GTDB_release202/kraken2/database250mers.kmer_distrib
2022-02-08 10:39:52,319 - Starting new HTTP connection (1): ftp.tue.mpg.de
2022-02-08 10:39:53,667 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release202/kraken2/hash.k2d HTTP/1.1" 200 237562711800
Traceback (most recent call last):
  File "./util_scripts/database_download.py", line 124, in <module>
    main(args)
  File "./util_scripts/database_download.py", line 119, in main
    args.output_dir, args.threads)
  File "./util_scripts/database_download.py", line 101, in dl_files
    pool.map(func, data.find_all('a'))
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb6 in position 0: invalid start byte
2022-02-08 10:39:53,672 - Starting new HTTP connection (1): ftp.tue.mpg.de
\-----------------------


### Python3 log
\-----------------------
nohup: ignoring input
2022-02-08 10:58:08,598 - Starting new HTTP connection (1): ftp.tue.mpg.de:80
2022-02-08 10:58:09,947 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release202/kraken2 HTTP/1.1" 301 275
2022-02-08 10:58:10,215 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release202/kraken2/ HTTP/1.1" 200 5039
2022-02-08 10:58:10,271 - Starting new HTTP connection (1): ftp.tue.mpg.de:80
2022-02-08 10:58:10,272 - Starting new HTTP connection (1): ftp.tue.mpg.de:80
2022-02-08 10:58:10,274 - Starting new HTTP connection (1): ftp.tue.mpg.de:80
2022-02-08 10:58:10,275 - Starting new HTTP connection (1): ftp.tue.mpg.de:80
2022-02-08 10:58:11,621 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release202/kraken2/database100mers.kraken HTTP/1.1" 200 273571194
2022-02-08 10:58:11,622 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release202/kraken2/database75mers.kraken HTTP/1.1" 200 481357069
2022-02-08 10:58:11,623 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release202/kraken2/database150mers.kraken HTTP/1.1" 200 353523859
2022-02-08 10:58:11,624 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release202/kraken2/database200mers.kraken HTTP/1.1" 200 258230018
2022-02-08 11:05:43,159 - File written: custom_dbs/GTDB_release202/kraken2/database100mers.kraken
2022-02-08 11:05:43,161 - Starting new HTTP connection (1): ftp.tue.mpg.de:80
2022-02-08 11:05:44,515 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release202/kraken2/database150mers.kmer_distrib HTTP/1.1" 200 6688497
2022-02-08 11:06:15,104 - File written: custom_dbs/GTDB_release202/kraken2/database150mers.kmer_distrib
2022-02-08 11:06:15,114 - Starting new HTTP connection (1): ftp.tue.mpg.de:80
2022-02-08 11:06:16,489 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release202/kraken2/database250mers.kraken HTTP/1.1" 200 258893052
2022-02-08 11:08:03,464 - File written: custom_dbs/GTDB_release202/kraken2/database200mers.kraken
2022-02-08 11:08:03,467 - Starting new HTTP connection (1): ftp.tue.mpg.de:80
2022-02-08 11:08:05,346 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release202/kraken2/database250mers.kmer_distrib HTTP/1.1" 200 4007536
2022-02-08 11:08:17,824 - File written: custom_dbs/GTDB_release202/kraken2/database250mers.kmer_distrib
2022-02-08 11:08:17,828 - Starting new HTTP connection (1): ftp.tue.mpg.de:80
2022-02-08 11:08:19,176 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release202/kraken2/hash.k2d HTTP/1.1" 200 237562711800
2022-02-08 11:09:13,231 - File written: custom_dbs/GTDB_release202/kraken2/database150mers.kraken
2022-02-08 11:09:13,236 - Starting new HTTP connection (1): ftp.tue.mpg.de:80
2022-02-08 11:09:14,610 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release202/kraken2/database200mers.kmer_distrib HTTP/1.1" 200 4318492
2022-02-08 11:09:31,377 - File written: custom_dbs/GTDB_release202/kraken2/database200mers.kmer_distrib
2022-02-08 11:14:07,300 - File written: custom_dbs/GTDB_release202/kraken2/database250mers.kraken
2022-02-08 11:14:07,305 - Starting new HTTP connection (1): ftp.tue.mpg.de:80
2022-02-08 11:14:08,943 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release202/kraken2/database_mers.md5 HTTP/1.1" 200 598
2022-02-08 11:14:08,945 - File written: custom_dbs/GTDB_release202/kraken2/database_mers.md5
2022-02-08 11:17:03,101 - File written: custom_dbs/GTDB_release202/kraken2/database75mers.kraken
2022-02-08 11:17:03,104 - Starting new HTTP connection (1): ftp.tue.mpg.de:80
2022-02-08 11:17:04,455 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release202/kraken2/database100mers.kmer_distrib HTTP/1.1" 200 5096095
2022-02-08 11:17:18,441 - File written: custom_dbs/GTDB_release202/kraken2/database100mers.kmer_distrib
Traceback (most recent call last):
  File "./util_scripts/database_download.py", line 124, in <module>
    main(args)
  File "./util_scripts/database_download.py", line 118, in main
    dl_files(args.base_url, release, db,
  File "./util_scripts/database_download.py", line 101, in dl_files
    pool.map(func, data.find_all('a'))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 768, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 537, in _handle_tasks
    put(task)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/usr/local/lib/python3.8/dist-packages/bs4/element.py", line 954, in __getnewargs__
    return (str(self),)
RecursionError: maximum recursion depth exceeded while calling a Python object
\-----------

**Comment by nick-youngblut** [comment]
OK, this should now be fixed. It was a decoding issue. I've tested it with the kraken2 databases, and it now works. Sorry for the problems!

**Comment by emaxortiz** [comment]
Hi Nick,
I'm still getting the same error after using the fixed code for database_download.py.

2022-05-05 23:07:54,059 - File written: custom_dbs/GTDB_release202/kraken2/hash.k2d
Traceback (most recent call last):
  File "/home/eortiz/Struo2/util_scripts/database_download.py", line 138, in <module>
    main(args)
  File "/home/eortiz/Struo2/util_scripts/database_download.py", line 132, in main
    dl_files(args.base_url, release, db,
  File "/home/eortiz/Struo2/util_scripts/database_download.py", line 115, in dl_files
    pool.map(func, data.find_all('a'))
  File "/home/eortiz/.conda/envs/struo2/lib/python3.10/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/eortiz/.conda/envs/struo2/lib/python3.10/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/home/eortiz/.conda/envs/struo2/lib/python3.10/multiprocessing/pool.py", line 537, in _handle_tasks
    put(task)
  File "/home/eortiz/.conda/envs/struo2/lib/python3.10/multiprocessing/connection.py", line 211, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/eortiz/.conda/envs/struo2/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/eortiz/.conda/envs/struo2/lib/python3.10/site-packages/bs4/element.py", line 956, in __getnewargs__
    return (str(self),)
RecursionError: maximum recursion depth exceeded while calling a Python object.

Any guidance about how to solve this? I was thinking to increase the recursion limit but I'm not a 100% sure how (also not recommended in some forums), I'm not a coding person but can modify/readapt some codes.

Thanks.
Max

**Comment by nick-youngblut** [comment]
@emaxortiz I can't reproduce your error. Can you please try to increase the maximum recursion limit, as described in https://stackoverflow.com/questions/31528600/beautifulsoup-runtimeerror-maximum-recursion-depth-exceeded? Let me know if that fixes the issue

**Comment by emaxortiz** [comment]
Hi Nick, 
Thank you so much for your quick reply and the suggestion, I'll keep that in mind. I managed to download the database "manually". Now I'm trying to include my MAGs, I'll get back to you if something is not working. Thanks.

**Comment by CaitlinSelway** [comment]
Hi @nick-youngblut, 

Unfortunately, I have come across the same error as @emaxortiz. 

When I first encountered this issue, it the script ran for ~1.5 days before showing the recursion error (I forgot to see how much data downloaded). I followed the recommendation to increase the recursion depth and I upped this to 50,000 from the standard 1,000. I also increase the threads from 4 to 16. Unfortunately, this has now crashed after 3 days with the recursion error occurring after downloading ~100GB of the hash.k2d file. 

Can I ask what recursion depth you are running at? Is there an alternative method to download the pre-built database?

Thanks, 
Caitlin 

This is the log from the latest run with 16 threads and a max recursion depth of 50,000
```
(struo2) [iidcsel@frgeneseq03 gtdb_preBuilt]$ /phe/tools/Struo2/util_scripts/database_download.py -t 16 -r 202 -d kraken2 metadata taxdump phylogeny -- custom_dbs
2022-07-04 12:31:23,023 - Starting new HTTP connection (1): ftp.tue.mpg.de:80
2022-07-04 12:31:24,878 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release202/kraken2 HTTP/1.1" 301 275
2022-07-04 12:31:24,900 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release202/kraken2/ HTTP/1.1" 200 5039
2022-07-04 12:31:24,955 - Starting new HTTP connection (1): ftp.tue.mpg.de:80
2022-07-04 12:31:24,958 - Starting new HTTP connection (1): ftp.tue.mpg.de:80
2022-07-04 12:31:24,959 - Starting new HTTP connection (1): ftp.tue.mpg.de:80
2022-07-04 12:31:24,960 - Starting new HTTP connection (1): ftp.tue.mpg.de:80
2022-07-04 12:31:24,963 - Starting new HTTP connection (1): ftp.tue.mpg.de:80
2022-07-04 12:31:24,963 - Starting new HTTP connection (1): ftp.tue.mpg.de:80
2022-07-04 12:31:24,964 - Starting new HTTP connection (1): ftp.tue.mpg.de:80
2022-07-04 12:31:24,964 - Starting new HTTP connection (1): ftp.tue.mpg.de:80
2022-07-04 12:31:24,965 - Starting new HTTP connection (1): ftp.tue.mpg.de:80
2022-07-04 12:31:24,966 - Starting new HTTP connection (1): ftp.tue.mpg.de:80
2022-07-04 12:31:24,966 - Starting new HTTP connection (1): ftp.tue.mpg.de:80
2022-07-04 12:31:24,967 - Starting new HTTP connection (1): ftp.tue.mpg.de:80
2022-07-04 12:31:24,968 - Starting new HTTP connection (1): ftp.tue.mpg.de:80
2022-07-04 12:31:24,980 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release202/kraken2/database_mers.md5 HTTP/1.1" 200 598
2022-07-04 12:31:24,982 - File written: custom_dbs/GTDB_release202/kraken2/database_mers.md5
2022-07-04 12:31:24,984 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release202/kraken2/database100mers.kmer_distrib HTTP/1.1" 200 5096095
2022-07-04 12:31:24,996 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release202/kraken2/database200mers.kraken HTTP/1.1" 200 258230018
2022-07-04 12:31:24,996 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release202/kraken2/database200mers.kmer_distrib HTTP/1.1" 200 4318492
2022-07-04 12:31:25,000 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release202/kraken2/database250mers.kmer_distrib HTTP/1.1" 200 4007536
2022-07-04 12:31:25,003 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release202/kraken2/database75mers.kraken HTTP/1.1" 200 481357069
2022-07-04 12:31:25,009 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release202/kraken2/database100mers.kraken HTTP/1.1" 200 273571194
2022-07-04 12:31:25,015 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release202/kraken2/database150mers.kmer_distrib HTTP/1.1" 200 6688497
2022-07-04 12:31:25,027 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release202/kraken2/database150mers.kraken HTTP/1.1" 200 353523859
2022-07-04 12:31:25,030 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release202/kraken2/database250mers.kraken HTTP/1.1" 200 258893052
2022-07-04 12:31:25,750 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release202/kraken2/k2d.md5 HTTP/1.1" 200 129
2022-07-04 12:31:25,751 - File written: custom_dbs/GTDB_release202/kraken2/k2d.md5
2022-07-04 12:31:25,821 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release202/kraken2/database75mers.kmer_distrib HTTP/1.1" 200 8092021
2022-07-04 12:31:25,903 - File written: custom_dbs/GTDB_release202/kraken2/database250mers.kmer_distrib
2022-07-04 12:31:26,092 - File written: custom_dbs/GTDB_release202/kraken2/database200mers.kmer_distrib
2022-07-04 12:31:26,412 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release202/kraken2/hash.k2d HTTP/1.1" 200 237562711800
2022-07-04 12:31:26,478 - File written: custom_dbs/GTDB_release202/kraken2/database100mers.kmer_distrib
2022-07-04 12:31:26,806 - Starting new HTTP connection (1): ftp.tue.mpg.de:80
2022-07-04 12:31:27,298 - File written: custom_dbs/GTDB_release202/kraken2/database150mers.kmer_distrib
2022-07-04 12:31:28,292 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release202/kraken2/hash.k2d HTTP/1.1" 200 237562711800
2022-07-04 12:31:35,437 - File written: custom_dbs/GTDB_release202/kraken2/database250mers.kraken
2022-07-04 12:31:36,385 - File written: custom_dbs/GTDB_release202/kraken2/database100mers.kraken
2022-07-04 12:31:38,542 - File written: custom_dbs/GTDB_release202/kraken2/database200mers.kraken
2022-07-04 12:31:41,758 - File written: custom_dbs/GTDB_release202/kraken2/database150mers.kraken
2022-07-04 12:31:46,834 - File written: custom_dbs/GTDB_release202/kraken2/database75mers.kraken
2022-07-04 12:32:09,841 - File written: custom_dbs/GTDB_release202/kraken2/database75mers.kmer_distrib
2022-07-06 19:14:43,164 - File written: custom_dbs/GTDB_release202/kraken2/hash.k2d
Traceback (most recent call last):
  File "/phe/tools/Struo2/util_scripts/database_download.py", line 138, in <module>
    main(args)
  File "/phe/tools/Struo2/util_scripts/database_download.py", line 132, in main
    dl_files(args.base_url, release, db,
  File "/phe/tools/Struo2/util_scripts/database_download.py", line 115, in dl_files
    pool.map(func, data.find_all('a'))
  File "/phe/tools/miniconda3/envs/struo2/lib/python3.10/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/phe/tools/miniconda3/envs/struo2/lib/python3.10/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/phe/tools/miniconda3/envs/struo2/lib/python3.10/multiprocessing/pool.py", line 537, in _handle_tasks
    put(task)
  File "/phe/tools/miniconda3/envs/struo2/lib/python3.10/multiprocessing/connection.py", line 211, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/phe/tools/miniconda3/envs/struo2/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/phe/tools/miniconda3/envs/struo2/lib/python3.10/site-packages/bs4/element.py", line 956, in __getnewargs__
    return (str(self),)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

and showing the amount of data downloaded 
```
(struo2) ]$ ll -h custom_dbs/GTDB_release202/kraken2/
total 100G
-rw-rw-r-- 1 4.9M Jul  4 12:31 database100mers.kmer_distrib
-rw-rw-r-- 1 261M Jul  4 12:31 database100mers.kraken
-rw-rw-r-- 1 6.4M Jul  4 12:31 database150mers.kmer_distrib
-rw-rw-r-- 1 338M Jul  4 12:31 database150mers.kraken
-rw-rw-r-- 1 4.2M Jul  4 12:31 database200mers.kmer_distrib
-rw-rw-r-- 1 247M Jul  4 12:31 database200mers.kraken
-rw-rw-r-- 1 3.9M Jul  4 12:31 database250mers.kmer_distrib
-rw-rw-r-- 1 247M Jul  4 12:31 database250mers.kraken
-rw-rw-r-- 1 7.8M Jul  4 12:32 database75mers.kmer_distrib
-rw-rw-r-- 1 460M Jul  4 12:31 database75mers.kraken
-rw-rw-r-- 1 598 Jul  4 12:31 database_mers.md5
-rw-rw-r-- 1 99G Jul  6 19:14 hash.k2d
-rw-rw-r-- 1 129 Jul  4 12:31 k2d.md5
```

**Comment by nick-youngblut** [comment]
@CaitlinSelway I'll look into the issue ASAP. For now, you can always use `wget` for downloading the files. `./util_scripts/database_download.py` is just a convenience script to help automate the download proecess.

**Comment by CaitlinSelway** [comment]
Hi Nick,

thank you for the quick reply! Unfortunately `wget` isn’t working due to a 502 connection refused issue. 

I’ll have a try using 1 thread tomorrow. I’ll let you know if this was successful or not.

Thanks,
Caitlin

**Comment by nick-youngblut** [comment]
Maybe `wget` is configured oddly for you. You might want to check `~/.wgetrc`

**Comment by CaitlinSelway** [comment]
Thank you very much for the new release!
